version: 0.0
os: linux
files:
  - source: target/ROOT.war
    destination: /opt/tomcat/webapps
hooks:
  BeforeInstall:
    - location: Scripts/stop.sh
  AfterInstall:
    - location: Scripts/stop.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/start.sh
      timeout: 3600
  ValidateService:
    - location: Scripts/test.sh
